name: Feature Request
description: Request a feature
labels:
  - 'T: feature'
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the problem or missing capability
    validations:
      required: true
  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: How would this benefit users in general?
    validations:
      required: true
  - type: textarea
    id: solution-idea
    attributes:
      label: Solution Idea
      description: >-
        Do you have an idea of how this might work? If so, provide details,
        examples, references, etc.
